name: Response Time CI
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
jobs:
  response-time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        with:
          command: response-time
